#!/usr/bin/zsh

###  myzshrc

export EDITOR=vim
export VISUAL=vim

export DROPBOX_PATH=$HOME/Dropbox/sync
export GOPATH=$HOME/dev
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/opt/mysql-client/bin

if [ $commands[yarn] ]; then
  export PATH="$PATH:$(yarn global bin)"
fi

# sync HISTFILE
if [ -d $DROPBOX_PATH ]; then
  export HISTFILE=$DROPBOX_PATH/zhistory
fi

eval $(/opt/homebrew/bin/brew shellenv)
if type brew &>/dev/null; then
  export FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit -u
fi

#### Custom

# mise(rtx)
if [ $commands[mise] ]; then
  eval "$(mise activate zsh)"
  . <(mise completion zsh) && compdef _mise mise
fi

# aliases
alias gp="git pull"
alias gpo="git pb"
alias grpo="gm && gpo && git remote prune origin"
alias gm='git checkout "$(git symbolic-ref refs/remotes/origin/HEAD | cut -d'/' -f4)"'
alias gamend="git add . && git commit --amend --no-edit"
alias gs="git status"
alias gd="git diff"
alias gc="git cleanup"
alias gam="git commit -am"

# kubernetes
if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
  alias k="kubectl"
  alias kg="k get"
  alias kgpo="kg pod"
  alias kl="kubetail"
  alias kc="kubectx"
  alias kn="kubens"

  autoload -U colors
  colors
  source $(brew --prefix)/etc/zsh-kubectl-prompt/kubectl.zsh
  # RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'

  if [ -d $DROOPBOX_PATH ]; then
    export KUBECONFIG=$DROPBOX_PATH/kubeconfig
  fi
fi

# peco inc search
function peco-history-selection() {
  BUFFER=$(history -n 1 | tail -r | awk '!a[$0]++' | peco)
  CURSOR=$#BUFFER
  zle reset-prompt
}
zle -N peco-history-selection
bindkey '^R' peco-history-selection

# peco ghq
function peco-src() {
  local selected_dir=$(ghq list -p | peco --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
  fi
  zle clear-screen
}
zle -N peco-src
bindkey '^]' peco-src

if [ $commands[thefuck] ]; then
  eval $(thefuck --alias)
fi

if [ $commands[direnv] ]; then
  eval "$(direnv hook zsh)"
fi

if [ $commands[tree] ]; then
  alias t="tree -C"
fi

# aqua https://aquaproj.github.io/
if [ $commands[aqua] ]; then
  export PATH="$(aqua root-dir)/bin:$PATH"
fi

# rust
if [ -f $HOME/.cargo/env ]; then
  . "$HOME/.cargo/env"
fi

# gcloud
if [ $commands[gcloud] ]; then
  export PATH="$HOME/google-cloud-sdk/bin:$PATH"
  source $(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
  source $(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
fi

# 1password
if [ $commands[op] ]; then
  eval "$(op completion zsh)"
  compdef _op op
fi

export GPG_TTY=$(tty)

# source local rc
if [ -f $DROPBOX_PATH/myzshrc_local ]; then
  source $DROPBOX_PATH/myzshrc_local
fi

### end of myzshrc
