#!/usr/bin/zsh

###  myzshrc

export EDITOR=vim
export VISUAL=vim

export GOPATH=$HOME/dev

export PATH=$PATH:$GOPATH/bin
export PATH="$PATH:$(yarn global bin)"

# sync HISTFILE
if [ -f $HOME/Dropbox/zhistory ] ; then
    HISTFILE=$HOME/Dropbox/zhistory
fi

# source local rc
if [ -f $HOME/Dropbox/myzshrc_local ] ; then
    source $HOME/Dropbox/myzshrc_local
fi

# anyenv
if [ -d $HOME/.anyenv ] ; then
    export PATH="$HOME/.anyenv/bin:$PATH"
    eval "$(anyenv init -)"
fi

# aliases
alias gp="git pull"
alias gm="git checkout master"
alias gs="git status"
alias gd="git diff"
alias gc="git cleanup"
alias gam="git commit -am"

# kubernetes
if [ $commands[kubectl] ]; then
    source <(kubectl completion zsh)
    alias k="kubectl"
    alias kg="k get"
    alias kgpo="kg pod"
    alias kl="kubetail"
    alias kc="kubectx"
    alias kn="kubens"

    autoload -U colors; colors
    source /usr/local/etc/zsh-kubectl-prompt/kubectl.zsh
    RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
fi

# peco inc search
function peco-history-selection() {
    BUFFER=`history -n 1 | tail -r  | awk '!a[$0]++' | peco`
    CURSOR=$#BUFFER
    zle reset-prompt
}
zle -N peco-history-selection
bindkey '^R' peco-history-selection

# peco ghq
function peco-src () {
  local selected_dir=$(ghq list -p | peco --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
  fi
  zle clear-screen
}
zle -N peco-src
bindkey '^]' peco-src

if [ $commands[kubectl] ]; then
  eval $(thefuck --alias)
fi

### end of myzshrc
